### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by redheadt** [lucisgit/docker-debuild#1]
Hello, 
thank you for sharing this project. I tried to use it to build a .deb package from a binary, but unfortunately the documentation is shadowing for me. 
Could you help me out with my issues? 
Kind regards.

**Comment by kabalin** [comment]
Hi @redheadt, thanks for reaching out. If you want to use this tool for building a package, you need your repository prepared for Debian packaging, i.e. it should contain `./debian` directory with `control`, `changelog`, `rules` and `copyright` files as minimum, but explaining the process of preparing your code for packaging is beyond purpose of this tool. There are some manuals in the internet covering various scenarios, e.g. for something simple like packaging a script or single binary you can find this one useful https://blog.packagecloud.io/eng/2016/12/15/howto-build-debian-package-containing-simple-shell-scripts/
